version: 2

sources:

  # ── Source: DW_SP_CWA (biprod-gendw01.bi.scalepoint.lan\scalepoint) ──────────
  # All CWA tables live in the cwa schema of DW_SP_CWA on this server.
  - name: cwa
    database: DW_SP_CWA
    schema: cwa
    description: CWA data warehouse layer on biprod-gendw01.bi.scalepoint.lan\scalepoint
    tables:
      - name: FinancialDocument
      - name: FinancialDocumentLine
      - name: TaskDi
      - name: Case
      - name: Report
      - name: ReportLine
      - name: Service
      - name: ServiceProvider
